---
services:
  nextjs:
    build:
      context: .
      target: development
    volumes:
      - $PWD:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./.env.example

  mongo:
    image: mongo:7.0-jammy
    volumes:
      - db_data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    env_file:
      - ./.env.example

  mongo-express:
    image: mongo-express:1.0
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    env_file:
      - ./.env.example
    depends_on:
      - mongo

volumes:
  db_data:
